import json
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi
from dotenv import load_dotenv
import os

# Load environment variables from .env file
load_dotenv()
# Retrieve the password from the environment variable
mongo_password = os.getenv("MONGO_PASSWORD")

# MongoDB setup
uri = f"mongodb+srv://Nandini:{mongo_password}@2024-makeuc-hackathon.r3ow1.mongodb.net/?retryWrites=true&w=majority&appName=2024-MakeUC-Hackathon"
client = MongoClient(uri, server_api=ServerApi('1'))
db = client["2024MakeUCHackathonDB"]
login_data_collection = db["2024MakeUCHackathonFacts"]

# Environmental fun facts, scaled by level
level_facts = {
                "1": [
                "Recycling one plastic bottle can save enough energy to power a 60-watt light bulb for three hours.",
                "Switching to a reusable water bottle can save around 170 plastic bottles from waste each year.",
                "Turning off lights when you leave a room can save energy and reduce your electricity bill.",
                "Using a reusable coffee cup instead of disposable ones can save hundreds of cups from landfills every year.",
                "Recycling one aluminum can saves enough energy to run a TV for two hours.",
                "Reducing shower time by just one minute can save up to 150 gallons of water per month.",
                "Using cloth bags instead of plastic ones can keep hundreds of plastic bags out of the environment.",
                "Turning off your computer at night can save as much as $100 per year in electricity costs.",
                "Replacing old light bulbs with LEDs can reduce energy use by 75%.",
                "A single tree can absorb up to 48 pounds of CO2 each year, so planting one has big benefits.",
                "A single dripping faucet can waste over 3,000 gallons of water per year. Fixing leaks saves water and money.",
                "Using a programmable thermostat can save about 10% on heating and cooling costs.",
                "Using cold water for laundry can save energy and prevent about 1,600 pounds of CO2 emissions annually.",
                "Recycling glass reduces water pollution by 50% and air pollution by 20% compared to making new glass.",
                "Using natural light instead of artificial lighting during the day reduces energy consumption.",
                "Choosing carpooling just once a week can save up to 1,000 pounds of CO2 emissions annually.",
                "Eating locally grown food reduces food miles and the carbon footprint of food transportation.",
                "A full dishwasher uses less water than hand-washing dishes. Running full loads saves water and energy.",
                "Setting your fridge temperature to 37°F and freezer to 0°F saves energy.",
                "Reducing meat consumption just one day a week can save thousands of gallons of water per year.",
                "Composting food waste reduces methane emissions from landfills and produces natural fertilizer.",
                "Using a ceiling fan instead of air conditioning can save a lot of energy in warmer months.",
                "A single reusable straw can replace hundreds of disposable plastic straws over its lifetime.",
                "Using public transportation reduces greenhouse gas emissions and helps reduce road congestion.",
                "Collecting rainwater for your plants conserves water and helps them thrive without chemical treatments.",
                "Reducing junk mail can save paper and reduce deforestation.",
                "Using a reusable razor instead of disposable ones reduces plastic waste.",
                "Unplugging chargers when not in use can prevent phantom energy use and reduce electricity bills.",
                "Buying secondhand items reduces demand for new products and conserves resources.",
                "Eating less beef can lower your carbon footprint because beef production generates high emissions.",
                "Using a drying rack instead of a dryer can save energy and make clothes last longer.",
                "An average plastic bottle takes 450 years to decompose. Recycling can prevent long-term waste.",
                "Driving at 55 mph instead of 65 mph can improve fuel efficiency by up to 15%.",
                "Using rechargeable batteries instead of disposables reduces toxic waste in landfills.",
                "If every home used a low-flow showerhead, the U.S. could save billions of gallons of water yearly.",
                "One meatless meal per week can save the energy equivalent of driving 1,160 miles per year.",
                "If everyone used a reusable shopping bag, it could save billions of plastic bags each year.",
                "Switching off power strips saves energy from devices in standby mode.",
                "Using a handkerchief instead of tissues saves trees and reduces waste.",
                "For every mile you walk instead of drive, you prevent about one pound of CO2 from entering the air.",
                "Air drying your hair instead of using a dryer can save a significant amount of energy.",
                "A reusable lunchbox can replace hundreds of disposable bags over the course of a year.",
                "Biking instead of driving for short trips reduces pollution and saves money.",
                "Using eco-friendly cleaning products reduces pollution in water systems.",
                "A single mature tree produces enough oxygen for two people to breathe for a year.",
                "Collecting plastic bags and recycling them prevents litter and keeps them out of the environment.",
                "If every American recycled their Sunday newspaper, it would save 500,000 trees weekly.",
                "Donating clothes instead of throwing them away reduces landfill waste.",
                "Walking or biking to work reduces greenhouse gas emissions and promotes better health.",
                "Choosing paperless billing helps reduce paper waste and saves trees.",
                "Reducing thermostat settings by 1°F in winter can save 1% on heating bills."
            ],
        "2": [
        "Each ton of recycled paper can save 17 trees from being cut down.",
        "Turning off your car engine when parked can reduce air pollution and save fuel.",
        "Recycling one ton of glass can save around 42 kWh of energy, reducing local energy demands.",
        "Carpooling with friends can reduce vehicle emissions and improve local air quality.",
        "Using public transportation in a city reduces overall greenhouse gas emissions significantly.",
        "Planting native trees in your area supports local wildlife and improves air quality.",
        "A community garden helps improve soil quality, promotes biodiversity, and strengthens community ties.",
        "For every pound of beef not eaten, around 1,800 gallons of water are saved.",
        "Adopting energy-efficient appliances as a community can lower the area's total energy demand.",
        "Encouraging composting locally reduces waste sent to landfills and improves soil quality.",
        "Using rain barrels to collect water reduces strain on community water supplies.",
        "One ton of recycled steel can conserve 2,500 pounds of iron ore and reduce mining impact.",
        "Switching to LED street lights in a neighborhood can save energy and reduce city emissions.",
        "Participating in local clean-up drives can reduce litter and improve neighborhood aesthetics.",
        "Recycling 100 pounds of plastic can prevent 500 pounds of CO2 emissions.",
        "Reducing lawn watering saves up to 50% of residential water use in some communities.",
        "Advocating for bike lanes promotes cycling, reducing car pollution and congestion.",
        "Volunteering to pick up trash in parks helps protect local wildlife and keeps the area clean.",
        "Composting food waste at home and in the community reduces landfill methane emissions.",
        "Using electric lawn equipment can reduce local air pollution caused by gasoline-powered machines.",
        "Replacing old refrigerators with energy-efficient models as a community can save substantial energy.",
        "Encouraging solar panel installations reduces the local grid's reliance on fossil fuels.",
        "Recycling one ton of aluminum saves about 10 cubic yards of landfill space.",
        "Swapping a community event to be zero-waste reduces the total waste generated.",
        "Promoting local farm produce reduces the need for long-distance food transportation.",
        "Setting up shared recycling facilities makes recycling more accessible to everyone.",
        "Creating wildlife corridors in urban areas helps animals move safely between habitats.",
        "Advocating for green roofs on community buildings improves air quality and reduces heat.",
        "Every ton of newspaper recycled can save enough energy to power a home for six months.",
        "Starting a book swap in a neighborhood reduces paper waste and promotes reuse.",
        "For each plastic bottle recycled, enough energy is saved to run a 100-watt bulb for four hours.",
        "Hosting a community clothes swap prevents unnecessary textile waste.",
        "Recycling electronics reduces the need for harmful metal mining and disposal.",
        "Encouraging water-saving fixtures in the community saves thousands of gallons of water.",
        "A single mature tree provides cooling worth $10 per year in energy savings.",
        "Installing smart meters in homes allows communities to reduce peak energy usage.",
        "Encouraging native plant gardens helps reduce the need for pesticides and fertilizers.",
        "Local tree-planting initiatives can reduce neighborhood air pollution.",
        "Promoting paperless offices or schools saves countless trees and reduces waste.",
        "Turning off outdoor lights at night helps reduce light pollution, aiding local wildlife.",
        "Organizing a community e-waste collection event can safely dispose of toxic materials.",
        "Swapping lawn mowers for native plants reduces maintenance and provides wildlife habitat.",
        "Using greywater systems in homes can reduce community water usage.",
        "Recycling just 10% more newspapers could save 25 million trees a year.",
        "Encouraging hybrid and electric vehicles reduces neighborhood air and noise pollution.",
        "Reducing plastic use at community events lowers the amount of waste produced.",
        "Organizing a reusable bag swap promotes reduced reliance on single-use plastics.",
        "Creating neighborhood recycling drop-off spots improves waste management practices.",
        "Implementing community composting bins reduces landfill waste and enriches local soil.",
        "Using energy-efficient outdoor lighting in a neighborhood reduces light pollution."
    ],

    "3": [
    "One tree can absorb up to 48 pounds of carbon dioxide per year, making trees essential for carbon capture.",
    "Composting organic waste can reduce landfill space, which reduces greenhouse gas emissions.",
    "Planting community trees can lower city temperatures by up to 10°F in some urban areas.",
    "Replacing one city block's worth of asphalt with greenery can help manage stormwater and reduce flooding risks.",
    "Public transit systems can reduce a city’s carbon footprint by thousands of tons annually.",
    "Creating green roofs on city buildings can reduce urban heat by absorbing sunlight and cooling the area.",
    "Recycling glass saves 30% of the energy it would take to produce new glass from raw materials.",
    "Switching to electric buses in a city can significantly cut down on diesel pollution and improve air quality.",
    "Installing solar panels on city buildings can power entire neighborhoods sustainably.",
    "Banning plastic bags in a city prevents millions of tons of plastic waste annually.",
    "LED streetlights save up to 50% more energy than conventional streetlights.",
    "A community-wide push for recycling can reduce landfill waste by up to 25%.",
    "Using permeable pavements in neighborhoods helps reduce stormwater runoff and prevent flooding.",
    "A well-established urban forest can reduce city noise pollution by acting as a natural sound barrier.",
    "Encouraging city compost programs diverts up to 50% of waste from landfills.",
    "Green parks in urban areas improve local air quality by capturing pollutants.",
    "A citywide bike-share program can reduce reliance on cars and lower transportation emissions.",
    "Installing rooftop gardens on city buildings helps reduce energy use by providing natural insulation.",
    "Switching to low-flush toilets in city buildings can save hundreds of thousands of gallons of water annually.",
    "Urban forests provide shade, which can lower air conditioning costs in the surrounding area by 20%.",
    "A single bus reduces the need for over 30 cars on the road, lowering pollution and congestion.",
    "Using rain gardens in public spaces helps capture runoff, preventing local water pollution.",
    "Incorporating green building codes can reduce a city's overall energy consumption by up to 30%.",
    "Cities with well-maintained parks tend to have lower crime rates, promoting overall community health.",
    "Public water bottle refill stations reduce plastic bottle waste significantly in urban areas.",
    "Encouraging xeriscaping in public spaces can cut water usage for landscaping by up to 50%.",
    "Reducing car idling in cities can decrease harmful emissions, improving local air quality.",
    "A single car-free day in a city can reduce CO2 emissions by thousands of tons.",
    "A community tree-planting drive can absorb enough CO2 to equal driving over a million miles.",
    "Switching to electric delivery vehicles in a city lowers emissions and noise pollution.",
    "Installing wind turbines on city-owned land can generate clean electricity for thousands of homes.",
    "Encouraging water conservation in cities can lower water treatment energy costs.",
    "Zero-waste programs in neighborhoods can reduce landfill-bound waste by up to 40%.",
    "Promoting backyard gardens in cities helps reduce food miles and emissions associated with food transport.",
    "Banning Styrofoam in a city can significantly reduce local land and water pollution.",
    "Using reclaimed water in public parks conserves freshwater and lowers city water bills.",
    "Setting up electric vehicle charging stations encourages green transportation options.",
    "An urban green wall can improve air quality and reduce noise pollution on busy streets.",
    "Recycling aluminum cans across a city saves enough energy to power thousands of homes.",
    "Installing low-flow water fixtures in public buildings saves millions of gallons of water annually.",
    "Reducing single-use plastic in city events lowers waste and promotes sustainability.",
    "Community repair events help reduce waste by fixing items instead of discarding them.",
    "Tree-planting projects reduce soil erosion and help maintain soil quality in urban spaces.",
    "Implementing urban agriculture initiatives provides fresh produce, lowering food transport emissions.",
    "Creating car-free zones in city centers reduces pollution and enhances air quality.",
    "Promoting community composting reduces waste and provides free natural fertilizer.",
    "Switching public transport to biofuels cuts greenhouse gas emissions from city buses.",
    "Encouraging telecommuting can reduce commuter traffic and associated pollution.",
    "Urban wetlands can naturally treat wastewater, improving local water quality.",
    "Setting up community solar farms can provide affordable green energy to lower-income neighborhoods."
]
,

    "4": [
    "If everyone in the U.S. recycled their newspaper, it could save 250 million trees each year.",
    "Reducing shower time by just one minute can save over 150 gallons of water per month.",
    "Switching to energy-efficient appliances can cut household energy use by up to 30%.",
    "If everyone turned off their lights for one hour a day, it would prevent millions of tons of CO2 emissions annually.",
    "Switching to LED bulbs saves up to 80% of the energy used by incandescent bulbs.",
    "Using reusable shopping bags can save billions of plastic bags from ending up in landfills each year.",
    "Reducing meat consumption by one meal a week can save over 1,500 gallons of water annually.",
    "If everyone composted their food waste, it would reduce methane emissions from landfills significantly.",
    "Air drying clothes instead of using a dryer can save hundreds of pounds of CO2 emissions per household each year.",
    "Carpooling to work just twice a week reduces traffic congestion and air pollution substantially.",
    "Choosing locally-sourced foods reduces the carbon footprint associated with long-distance food transport.",
    "If everyone in a community recycled aluminum cans, it would save enough energy to power thousands of homes.",
    "Reducing junk mail could save millions of trees each year and reduce landfill waste.",
    "Switching to a programmable thermostat can lower household energy bills by up to 10%.",
    "If half of all Americans used public transportation, it could reduce CO2 emissions by millions of tons annually.",
    "Planting a small vegetable garden can reduce the need for food transportation and lower carbon emissions.",
    "Avoiding single-use plastics could reduce global plastic waste by over 40%.",
    "If every U.S. household replaced one roll of paper towels with recycled paper towels, it would save millions of trees.",
    "Switching to plant-based cleaning products reduces water pollution and improves local water quality.",
    "Cutting down on paper usage by using digital options can save millions of trees every year.",
    "Choosing energy-efficient vehicles can reduce greenhouse gas emissions significantly for a household.",
    "Using a rain barrel to collect rainwater for gardening conserves water and reduces utility bills.",
    "If every household planted one tree, it would absorb tons of CO2 and provide fresh oxygen.",
    "Encouraging work-from-home policies can reduce commuter traffic and air pollution citywide.",
    "Each household using solar panels could prevent thousands of pounds of CO2 emissions per year.",
    "Switching to reusable containers prevents plastic pollution and reduces landfill waste.",
    "By conserving energy at home, a community can reduce its overall carbon footprint substantially.",
    "Every household switching to organic food choices can reduce pesticide runoff and improve soil health.",
    "Recycling electronics reduces the demand for mining new metals and saves valuable resources.",
    "Reducing food waste by meal planning can save families money and reduce methane from landfills.",
    "Participating in a community clean-up improves the environment and reduces local pollution levels.",
    "Swapping bottled water for a reusable bottle can save hundreds of plastic bottles annually per person.",
    "Avoiding fast fashion and choosing sustainable clothing can reduce landfill waste and pollution.",
    "Installing water-saving showerheads conserves thousands of gallons of water per household annually.",
    "If every household in a neighborhood reduced heating by 1 degree, it could save tons of CO2 emissions each year.",
    "Encouraging eco-friendly landscaping saves water, reduces pesticide use, and lowers carbon footprints.",
    "Reducing the frequency of lawn mowing lowers emissions and improves air quality.",
    "If every household used a compost bin, it would reduce waste going to landfills by a significant margin.",
    "Switching to paperless billing reduces paper waste and saves trees.",
    "Installing window insulation reduces energy costs and improves household energy efficiency.",
    "Switching to natural gas or solar heating can reduce community-wide carbon emissions drastically.",
    "Car-free days in neighborhoods can decrease local pollution and encourage alternative transportation.",
    "If all households avoided palm oil products, it would help reduce deforestation rates globally.",
    "Reducing the use of pesticides in home gardening improves biodiversity and protects pollinators.",
    "Buying in bulk reduces packaging waste and lowers plastic pollution levels.",
    "Supporting local organic farms reduces pollution from transportation and pesticide use.",
    "Reducing the use of plastic wrap by switching to beeswax wraps prevents single-use plastic waste.",
    "If everyone turned off unused electronics, it would prevent tons of CO2 emissions each year.",
    "Using low-flow faucets saves water and reduces the energy needed for heating it.",
    "If every community planted a green space, it would improve air quality and reduce urban heat.",
    "Adopting electric scooters or bikes for short commutes reduces traffic and emissions in cities."
]
,

    "5": [
    "Producing one hamburger uses enough water to fill 15 bathtubs. Reducing meat consumption saves water and reduces emissions.",
    "A standard solar panel can offset over 10 tons of CO2 emissions in its lifetime.",
    "Recycling one ton of aluminum saves about 40 barrels of oil.",
    "Driving a fuel-efficient car can save thousands of pounds of CO2 emissions annually.",
    "Reducing air conditioner use can save hundreds of dollars on electricity bills and reduce carbon footprint.",
    "Switching to electric vehicles can reduce greenhouse gas emissions by up to 50% compared to gasoline cars.",
    "Energy-efficient windows reduce heating and cooling needs, cutting energy bills by 15-20%.",
    "A household compost bin can save over 600 pounds of organic waste from landfills each year.",
    "Transitioning to a plant-based diet can lower an individual’s carbon footprint by up to 73%.",
    "Using a programmable thermostat saves about 10% on heating and cooling costs.",
    "Growing your own vegetables reduces the carbon footprint of food transportation and packaging.",
    "Using public transportation instead of a car can reduce carbon emissions by 4,800 pounds per person per year.",
    "Switching from bottled to filtered tap water prevents thousands of plastic bottles from entering landfills.",
    "Turning off electronics when not in use could save over 10% of a household’s annual electricity consumption.",
    "Shifting from gas to electric cooking appliances can reduce home carbon emissions.",
    "One reusable bag can replace up to 500 single-use plastic bags per year.",
    "If everyone recycled plastic bottles, it would save enough energy to power millions of homes.",
    "Using low-emission wood stoves can reduce air pollution and improve indoor air quality.",
    "Solar water heaters can save homeowners 50-80% on their water heating bills.",
    "Cycling or walking instead of driving short distances can reduce urban pollution and improve air quality.",
    "Reducing shower time to five minutes can save around 1,000 gallons of water per year.",
    "If half the population adopted a zero-waste lifestyle, waste in landfills would drop by 40%.",
    "Installing insulation can reduce a household’s energy needs by up to 25%, cutting costs and emissions.",
    "Switching to locally-sourced, seasonal produce cuts down on the carbon emissions from food transport.",
    "Electric bikes for commuting reduce congestion and save fuel, cutting emissions by half compared to cars.",
    "Planting drought-resistant plants reduces water usage in gardens and conserves local water resources.",
    "If 25% of a community used rainwater harvesting systems, it would reduce municipal water demand by millions of gallons.",
    "Solar panels on a community scale could power hundreds of homes, cutting fossil fuel dependency.",
    "Adopting greywater recycling at home can save thousands of gallons of water each year.",
    "Replacing traditional light bulbs with LEDs in public areas could reduce city electricity costs by millions annually.",
    "Shifting to energy-efficient appliances nationwide could save enough energy to power 32 million homes.",
    "Installing green roofs can reduce urban heat and save up to 20% on energy costs in buildings.",
    "By avoiding single-use plastic straws, a community could prevent tons of plastic waste from entering oceans.",
    "Switching to online billing for utilities saves forests from paper production and reduces pollution.",
    "Using reclaimed wood for home projects reduces demand for logging and preserves forest ecosystems.",
    "Each pound of recycled paper saves about 3.5 pounds of carbon dioxide emissions.",
    "Replacing old water heaters with energy-efficient models can save hundreds of dollars in energy bills per year.",
    "Participating in local clean-up drives improves community spaces and reduces pollution.",
    "Switching to natural cleaning products protects water sources from harmful chemicals and improves water quality.",
    "Upgrading to a high-efficiency furnace can cut winter heating bills and reduce emissions.",
    "Choosing energy-efficient refrigerators can reduce home electricity use by up to 15%.",
    "Encouraging urban green spaces improves air quality and can reduce local temperatures by several degrees.",
    "Switching to a community garden initiative can save families money and reduce food miles.",
    "Turning off heated dryers in public restrooms reduces energy usage and saves businesses money.",
    "If all homes sealed air leaks, it could save enough energy to power over 15 million homes annually.",
    "Using a hand-push lawnmower instead of a gas mower reduces air pollution and saves fuel.",
    "Eating less beef can significantly lower an individual's ecological footprint and reduce deforestation.",
    "Reducing the use of chemical fertilizers in community parks preserves soil quality and prevents water pollution.",
    "Switching to recycled building materials for community projects can save energy and reduce waste.",
    "Adopting solar-powered outdoor lights reduces energy consumption and provides reliable lighting in public spaces.",
    "Growing bamboo in community areas captures carbon, grows quickly, and provides renewable resources."
]
,

    "6": [
    "Using energy-efficient light bulbs can reduce energy consumption by 75%, saving money and reducing carbon footprint.",
    "Electric vehicles reduce greenhouse gas emissions by up to 50% compared to gasoline vehicles.",
    "Switching to public transportation instead of commuting by car can save up to 20 pounds of CO2 emissions per day.",
    "Energy-efficient appliances can save households around $500 annually on electricity bills.",
    "Double-pane windows can improve insulation and reduce energy use for heating and cooling by up to 24%.",
    "Replacing an old refrigerator with an Energy Star model can save more than $270 over five years.",
    "Installing low-flow showerheads can cut water usage by 40% and save energy for water heating.",
    "Switching to smart thermostats can reduce energy use by up to 10%, cutting down on home heating and cooling costs.",
    "On-demand water heaters can save up to 30% more energy compared to traditional water heaters.",
    "A solar water heater can meet 60-70% of a household’s hot water needs, reducing reliance on fossil fuels.",
    "Using fans instead of air conditioning can reduce cooling costs by 50-90% in warm climates.",
    "LED lights last up to 25 times longer than incandescent bulbs and use 80% less energy.",
    "Switching to electric stoves reduces indoor air pollutants associated with gas stoves, improving air quality.",
    "Geothermal heating and cooling systems are 400% more efficient than conventional HVAC systems.",
    "Upgrading to efficient HVAC filters reduces energy waste and can lower HVAC-related electricity costs.",
    "Programmable thermostats can save households an estimated $180 annually on energy bills.",
    "Installing reflective roofing can reduce roof temperatures by 50°F, saving on cooling costs.",
    "Using energy-efficient computer equipment reduces electricity consumption in workplaces by up to 30%.",
    "If all U.S. households used efficient washing machines, the water saved could fill over 1 million Olympic pools.",
    "Recycling just one aluminum can saves enough energy to run a television for three hours.",
    "Energy-efficient freezers can save households around $150 annually in electricity costs.",
    "Solar-powered battery chargers reduce dependency on grid electricity, especially in sunny areas.",
    "Refrigerators with the freezer on top use less energy than side-by-side models, cutting energy bills.",
    "Planting shade trees around a home can reduce air conditioning costs by up to 25%.",
    "Switching to high-efficiency water heaters can cut water heating costs by up to 50%.",
    "Heat pump water heaters are 2-3 times more energy-efficient than conventional water heaters.",
    "Installing a water softener can improve the efficiency of home heating systems and reduce energy waste.",
    "Electricity from renewable sources in your home reduces your carbon footprint significantly.",
    "Switching to bamboo flooring reduces deforestation as bamboo grows faster and absorbs more CO2.",
    "Solar-powered outdoor lights are cost-effective and reduce demand on grid electricity for lighting.",
    "Using low-energy, high-efficiency washing machines reduces water waste by up to 50%.",
    "Installing energy-saving window treatments conserves heat in winter and keeps spaces cooler in summer.",
    "Insulating your water heater tank can reduce standby heat losses by 25-45%, saving energy.",
    "Switching to low-energy electronics like laptops instead of desktops saves 80% more electricity.",
    "Small actions like unplugging chargers can save up to 10% of household electricity usage annually.",
    "Air-sealing your home prevents drafts, reducing heating and cooling costs by up to 15%.",
    "If every household used a programmable thermostat, we could save 0.2 billion barrels of oil annually.",
    "One LED bulb used for three hours a day can save over 1,000 kWh of electricity over its lifetime.",
    "If all homes had efficient water heating, U.S. energy demand could drop by 15%.",
    "Reducing laundry by one load per week could save 300 pounds of CO2 per year.",
    "Using cold water for laundry saves energy and can reduce water heating costs by 90%.",
    "Replacing older furnaces with high-efficiency models can reduce heating costs by up to 30%.",
    "Choosing locally-sourced materials for building reduces transportation emissions significantly.",
    "Adding a storm door can increase energy efficiency by up to 45%, depending on the climate.",
    "If every home installed solar panels, it would save over 5 million tons of CO2 emissions each year.",
    "Switching to low-emission windows reduces home energy consumption by up to 20%.",
    "Composting organic waste prevents methane production in landfills, a potent greenhouse gas.",
    "If all homes used solar water heaters, we could reduce CO2 emissions by 20 million tons annually.",
    "Replacing a desktop computer with an Energy Star model can reduce its energy use by up to 60%."
],

    "7": [
    "Switching to a plant-based diet can cut an individual's food-related carbon emissions by up to 73%.",
    "A mature tree can absorb enough CO2 over its lifetime to offset emissions from a car driven 26,000 miles.",
    "Using renewable energy sources like wind and solar reduces dependence on fossil fuels drastically.",
    "Adopting an electric vehicle saves approximately 2.5 tons of greenhouse gas emissions per year.",
    "Investing in public transit infrastructure can reduce urban air pollution by up to 30%.",
    "Rooftop solar panels can power entire households and reduce carbon footprint by around 3 tons annually.",
    "Installing heat pumps in homes can cut CO2 emissions by nearly 70% compared to traditional heating.",
    "Switching to a zero-waste lifestyle reduces landfill waste and cuts down CO2 emissions significantly.",
    "Reducing dairy consumption cuts methane emissions, as livestock contribute to 14.5% of global emissions.",
    "An average electric vehicle owner can save over 5,000 gallons of gasoline over the car’s lifetime.",
    "LED streetlights in cities reduce municipal energy costs by 50% and improve sustainability.",
    "Reducing meat consumption even by one day a week can lower CO2 emissions substantially.",
    "Choosing green-certified products ensures lower environmental impacts from production to disposal.",
    "Reducing overall consumption of goods minimizes demand for resources and cuts down on pollution.",
    "Opting for bicycles over cars for short distances can decrease CO2 emissions by hundreds of pounds per year.",
    "Using energy-efficient HVAC systems cuts down on greenhouse gases and improves air quality.",
    "If every family went zero-waste, landfills would decrease significantly, improving public health.",
    "Conserving forests protects biodiversity, which is essential for ecosystem stability.",
    "Supporting reforestation projects can help offset personal carbon footprints over time.",
    "Using biodegradable packaging materials reduces plastic waste, a critical environmental hazard.",
    "Shifting to compostable materials for food packaging can prevent tons of landfill waste.",
    "Switching to 100% renewable energy in households could save 1 million barrels of oil per day.",
    "Conservation tillage in agriculture preserves soil health and reduces emissions from machinery.",
    "Reducing paper usage in offices by switching to digital saves millions of trees annually.",
    "Banning single-use plastics prevents marine pollution, protecting ocean ecosystems.",
    "Adopting vegan leather alternatives can reduce deforestation and lower industrial waste.",
    "Switching to energy-efficient air conditioning in cities could cut global emissions drastically.",
    "Reducing water waste preserves ecosystems and reduces the need for energy-intensive treatment.",
    "Using green roofs in urban areas improves insulation, reducing energy costs and emissions.",
    "If all farms used no-till practices, soil carbon storage would increase, benefiting the climate.",
    "Supporting wind energy projects can help transition regions from coal to clean energy.",
    "Switching to natural refrigerants cuts down on powerful greenhouse gases like HFCs.",
    "Planting urban forests enhances air quality and provides natural cooling in cities.",
    "Switching to organic farming improves soil health, leading to better carbon storage.",
    "Educating youth on climate change can encourage future sustainable practices.",
    "Installing home solar batteries reduces grid demand, supporting renewable energy integration.",
    "Upgrading power plants with cleaner technology reduces emissions and promotes green energy.",
    "Purchasing energy-efficient office equipment cuts business costs and reduces emissions.",
    "If 50% of the world’s power came from renewables, CO2 emissions could drop significantly.",
    "Converting waste into energy reduces landfill use and can generate renewable power.",
    "Switching to LED bulbs globally could cut CO2 emissions by around 1.4 gigatons annually.",
    "Reducing shipping-related emissions helps lower global CO2, promoting greener commerce.",
    "Investing in electric public buses reduces noise pollution and improves city air quality.",
    "If everyone planted a tree, billions of tons of CO2 could be removed from the atmosphere.",
    "Creating wetlands to treat wastewater improves water quality and restores ecosystems.",
    "Recycling metal reduces the need for mining, which disrupts ecosystems and releases CO2.",
    "Switching to eco-friendly building materials can drastically reduce construction emissions.",
    "Encouraging carpooling reduces traffic emissions and improves urban air quality.",
    "Switching to plant-based packaging prevents plastic pollution in oceans and landfills."
],

    "8": [
    "Globally, food waste contributes to 8% of total greenhouse gas emissions. Reducing food waste can have a significant impact.",
    "A single wind turbine can power up to 500 homes, showing the impact of renewable energy.",
    "The fashion industry accounts for 10% of global carbon emissions. Opting for sustainable fashion can reduce this footprint.",
    "Switching to solar energy could eliminate up to 1.6 billion tons of CO2 emissions each year.",
    "Reducing food waste by just 25% globally could feed all undernourished people on the planet.",
    "One day's worth of the world's paper waste could fill over 20,000 large garbage trucks.",
    "Every ton of recycled plastic saves about 5,774 kWh of energy, enough to power a home for six months.",
    "If everyone used public transportation, global emissions could be cut by 20% annually.",
    "Reducing bottled water consumption can prevent 1.5 million tons of plastic waste each year.",
    "Global deforestation rates are equivalent to losing a soccer field's worth of forest every second.",
    "Reducing deforestation and increasing forest cover could remove billions of tons of CO2 annually.",
    "Switching to electric heating in buildings could reduce global CO2 emissions by nearly 2 billion tons.",
    "Global food production uses nearly 70% of freshwater resources. Reducing meat consumption conserves water.",
    "By conserving wetlands, we can protect biodiversity and store vast amounts of carbon.",
    "Reducing energy use by just 5% worldwide could decrease greenhouse gas emissions by hundreds of millions of tons.",
    "If every household switched to energy-efficient appliances, the energy saved could power millions of homes.",
    "Switching to renewable energy for industrial production could reduce emissions by up to 40%.",
    "Every year, 1 trillion plastic bags are used worldwide, contributing to pollution and marine waste.",
    "Using 100% recycled paper in offices globally could save millions of trees every year.",
    "Phasing out coal power plants worldwide could reduce global CO2 emissions by around 20%.",
    "Switching to plant-based food globally could reduce agricultural emissions by 70%.",
    "If everyone globally reduced their water consumption by 10%, we could save over 1 trillion liters annually.",
    "Switching to sustainable agriculture can improve soil health, increasing global carbon storage.",
    "Replacing traditional cement with eco-friendly alternatives could reduce emissions by billions of tons.",
    "Recycling 1 ton of aluminum saves up to 10 tons of CO2 emissions compared to producing new aluminum.",
    "Global fisheries contribute to 1.3% of emissions. Sustainable fishing practices could lower this impact.",
    "If everyone turned off unused devices, global energy demand could be reduced by up to 7%.",
    "Switching to organic farming globally could reduce emissions by up to 10% and improve soil quality.",
    "The aviation industry produces 2% of global emissions. Switching to biofuels could reduce this by half.",
    "Preventing deforestation in the Amazon alone could cut down global emissions by over 1 billion tons annually.",
    "Reducing single-use plastics could save marine life and reduce the ocean's microplastic pollution.",
    "Phasing out gasoline vehicles worldwide could save 5.5 billion tons of CO2 by 2050.",
    "If everyone installed low-flow fixtures, global water consumption could decrease by 30%.",
    "Global transition to electric vehicles could reduce transportation emissions by 40%.",
    "Switching to LED lighting globally would cut electricity consumption by 15%.",
    "Switching to vegan diets could prevent 8 gigatons of CO2 emissions annually.",
    "Reducing waste in the construction industry could cut its environmental impact by 50%.",
    "Banning single-use plastic could reduce global plastic waste by over 30%.",
    "Reducing household energy use by 20% could reduce global emissions by nearly 5%.",
    "A 10% increase in energy efficiency in industries could cut emissions by billions of tons globally.",
    "Switching all global shipping to low-emission fuel could reduce emissions by over 1 billion tons annually.",
    "If everyone recycled electronics, it could save valuable resources and reduce landfill waste.",
    "Switching to green roofs worldwide could reduce urban heat and lower cooling energy use by 20%.",
    "Efficient public transportation systems could save billions of liters of fuel every year.",
    "Global paper use reduction by 25% would save millions of trees and reduce deforestation.",
    "Switching to biogas instead of fossil fuels could cut global emissions by hundreds of millions of tons.",
    "Composting organic waste globally could reduce landfill emissions by billions of tons of CO2 equivalent.",
    "Reducing household heating by 2°C in winter could save billions of tons of CO2.",
    "A global shift to renewable energy could save over 20 billion tons of CO2 per year.",
    "If all households globally used smart meters, energy efficiency could increase by 10%.",
    "Switching to reusable shopping bags could prevent billions of plastic bags from polluting the earth.",
    "Reducing global food waste by half could cut emissions by 4.4 billion tons of CO2 annually."
],

    "9": [
    "Deforestation accounts for nearly 15% of all greenhouse gas emissions annually, equivalent to the emissions from the global transportation sector.",
    "If everyone planted one tree, we could absorb up to 25% of current human-made CO2 emissions.",
    "The Amazon rainforest produces 20% of the world’s oxygen, yet deforestation is rapidly decreasing its capacity.",
    "Reducing global deforestation to zero could cut CO2 emissions by 2 billion tons each year.",
    "Transitioning to 100% renewable energy worldwide could prevent 1,500 coal-fired plants from operating.",
    "Global use of energy-efficient technologies could reduce emissions by over 10 billion tons per year.",
    "Switching to sustainable agriculture practices could reduce greenhouse gas emissions by up to 1.5 billion tons annually.",
    "The global livestock industry contributes nearly 18% of all greenhouse gas emissions; reducing meat consumption can lessen this impact.",
    "If every home in the U.S. installed solar panels, CO2 emissions could be reduced by over 1.2 billion tons annually.",
    "Banning plastic worldwide could prevent up to 12 million tons of plastic from entering oceans annually.",
    "The fashion industry uses 93 billion cubic meters of water per year; sustainable fashion can drastically reduce water usage.",
    "Reducing air travel globally by just 10% could prevent up to 200 million tons of CO2 emissions annually.",
    "Global protection of wetlands could help sequester an additional 830 million tons of CO2 per year.",
    "If food waste were a country, it would be the third-largest emitter of greenhouse gases globally.",
    "Switching to green hydrogen could reduce global CO2 emissions by up to 10% by 2050.",
    "A single meatless day worldwide could save over 170 million animals and reduce greenhouse emissions significantly.",
    "Protecting global peatlands could prevent the release of 550 gigatons of carbon into the atmosphere.",
    "If all people recycled paper globally, 2.5 million trees could be saved each day.",
    "Switching to electric heat pumps worldwide could reduce CO2 emissions by over 1 billion tons per year.",
    "Reducing urban heat by increasing green space could cut energy costs and emissions by up to 25%.",
    "A ban on plastic packaging could reduce global plastic pollution by up to 40%.",
    "Protecting the top 10 biodiversity hotspots could prevent the extinction of thousands of species.",
    "Switching to electric vehicles worldwide could save 10 billion barrels of oil annually.",
    "Global reforestation efforts could potentially capture over 200 gigatons of carbon by 2050.",
    "Phasing out fossil fuel subsidies could reduce global emissions by up to 10%.",
    "A shift to plant-based diets globally could free up 76% of agricultural land, reducing emissions drastically.",
    "Improving energy efficiency in buildings worldwide could save 6 billion tons of CO2 annually.",
    "Protecting primary forests alone could remove up to 2 billion tons of CO2 per year.",
    "Moving to zero-waste economies globally could save billions of tons of waste from landfills.",
    "Transitioning global cement production to green alternatives could reduce emissions by 8% annually.",
    "Sustainable fishing practices could increase fish populations, restoring marine ecosystems and enhancing biodiversity.",
    "Global soil restoration could capture an additional 1.7 billion tons of CO2 each year.",
    "Phasing out coal entirely could cut global emissions by 20% and prevent premature deaths due to air pollution.",
    "If all governments enforced environmental regulations strictly, air pollution could be reduced by 50%.",
    "Switching all cargo shipping to low-emission fuels could reduce global emissions by 2%.",
    "Using sustainable forest management worldwide could reduce emissions from deforestation by over 60%.",
    "Every degree Celsius reduction in building heating could save up to 10% in energy costs.",
    "Switching global agriculture to sustainable practices could reduce pesticide pollution by 80%.",
    "Banning palm oil production on deforested land could reduce deforestation by 30%.",
    "Switching to electric grids with battery storage could cut global emissions by 10%.",
    "Implementing a global carbon tax could decrease global emissions by 15% in the next decade.",
    "Ending global subsidies for fossil fuels could prevent up to 20% of CO2 emissions.",
    "Moving to zero-emission public transit systems could reduce transportation emissions by 40%.",
    "The protection of marine ecosystems could support carbon capture on a massive scale.",
    "Increasing recycling rates globally could save 1.1 billion tons of CO2 annually.",
    "If every household globally composted, we could cut landfill emissions by billions of tons of CO2.",
    "Switching to organic fertilizers globally could cut chemical fertilizer use by 40%, improving soil health.",
    "Increasing ocean protected areas to 30% could rebuild fish populations and stabilize ecosystems.",
    "Creating climate-resilient cities could reduce global emissions by 4 billion tons annually."
],

"10": [
    "Oceans absorb around 30% of the CO2 emitted into the atmosphere, but ocean acidification from excess CO2 threatens marine life.",
    "Protecting 30% of the planet’s land and oceans by 2030 could prevent mass extinctions and stabilize the climate.",
    "Switching to renewable energy could meet 80% of global energy needs, cutting emissions significantly.",
    "A worldwide shift to plant-based diets could reduce food-related emissions by 70%.",
    "Rising sea levels could displace millions of people by 2050 if action isn't taken on emissions.",
    "Transitioning to electric transportation worldwide could reduce oil demand by up to 25% by 2040.",
    "If all countries upheld the Paris Agreement, global temperatures could be kept within safe limits.",
    "Reducing global fossil fuel use by 50% could prevent severe climate consequences.",
    "The Arctic could be ice-free by 2040 if global warming continues at its current rate.",
    "Preserving global coral reefs could protect fisheries and biodiversity supporting over a billion people.",
    "Restoring 15% of converted lands worldwide could avoid 60% of expected extinctions.",
    "A global shift to low-carbon economies could reduce poverty while slowing climate change.",
    "If all industries adopt circular economies, waste generation could be halved worldwide.",
    "Protecting 50% of remaining wetlands could reduce flood damage and store massive amounts of CO2.",
    "Global biodiversity loss can disrupt ecosystems and food chains essential for human survival.",
    "Reducing deforestation rates by half could save 200,000 square miles of forest over 20 years.",
    "Removing carbon dioxide from the atmosphere could prevent severe climate tipping points.",
    "Switching all fossil fuel subsidies to renewable energy could drive down emissions drastically.",
    "The top 100 companies produce 71% of global emissions; corporate accountability is key to climate action.",
    "Ocean currents regulate global temperatures; climate change threatens these essential systems.",
    "Saving peatlands could prevent over 5% of annual global carbon emissions.",
    "Climate-resilient agriculture could secure food supply while reducing carbon emissions.",
    "If every household installed solar, energy needs could be met sustainably worldwide.",
    "Reducing global heating to 1.5°C could prevent severe weather events and ecosystem loss.",
    "Stopping the expansion of fossil fuel extraction could lower global emissions by billions of tons.",
    "Protecting mangrove forests could reduce 20 million tons of CO2 emissions yearly.",
    "Implementing reforestation globally could sequester 200 gigatons of carbon by 2050.",
    "Reducing energy waste in transportation could save the global economy trillions by 2050.",
    "If sustainable practices are adopted globally, freshwater scarcity could be alleviated by 2040.",
    "Transitioning to sustainable food systems globally could reduce emissions by up to 6.7 billion tons.",
    "Ending industrial fishing in protected areas could restore fish populations and biodiversity.",
    "Reducing air pollution worldwide could prevent 7 million premature deaths per year.",
    "Switching to plant-based diets worldwide could cut greenhouse gas emissions by over 60%.",
    "Phasing out coal entirely could prevent 800,000 premature deaths annually from pollution.",
    "Rebuilding degraded ecosystems could restore 15 million square miles of biodiversity.",
    "Switching to sustainable forestry could save 1.4 million square miles of forest cover.",
    "If all governments taxed carbon emissions, climate action could be expedited globally.",
    "Recycling rates of 100% worldwide could conserve resources and reduce emissions by billions of tons.",
    "Enforcing global air pollution standards could save lives and reduce healthcare costs.",
    "Ending deforestation globally could cut a quarter of total emissions annually.",
    "Switching to ocean-based energy could power the world sustainably without emissions.",
    "Global wetland restoration could capture over 100 gigatons of CO2 annually.",
    "Adopting sustainable land use practices could protect 40% of global biodiversity.",
    "Reducing plastic use by 90% could save marine ecosystems and prevent pollution.",
    "Protecting large carbon sinks like the Amazon could prevent severe climate impacts.",
    "Removing methane emissions from agriculture could lower global temperatures by 0.2°C.",
    "Reducing overfishing could restore ocean ecosystems and support coastal communities.",
    "Protecting endangered species worldwide could stabilize ecosystems and biodiversity.",
    "Implementing sustainable development goals could secure a livable planet for future generations."
]

}

# Convert the dictionary to JSON format and upload it to MongoDB
def upload_facts_to_mongo():
    try:
        # Insert the entire dictionary as a single document
        login_data_collection.insert_one({"level_facts": level_facts})
        print("Facts successfully uploaded to MongoDB!")
    except Exception as e:
        print(f"Error uploading facts to MongoDB: {e}")

# Call the function to perform the upload
upload_facts_to_mongo()
